# Generated by Django 3.2.10 on 2021-12-28 20:03

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kid Name')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)], verbose_name='Kid Age')),
                ('parent_email', models.EmailField(max_length=250, verbose_name='Parent Email')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+911234567890'. Up to 10 digits allowed.", regex='^\\+?1?\\d{10,15}$')], verbose_name='Parent Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('image_url', models.URLField()),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 12, 28, 20, 3, 4, 974044, tzinfo=utc), verbose_name='Created on')),
                ('updated_on', models.DateTimeField(default=datetime.datetime(2021, 12, 28, 20, 3, 4, 974044, tzinfo=utc), verbose_name='Updated on')),
                ('is_approved', models.BooleanField(default=False, verbose_name='is_approved')),
                ('food_group', models.CharField(choices=[('0', 'Veg'), ('1', 'Fruit'), ('2', 'Grain'), ('3', 'Protein'), ('4', 'Dairy'), ('5', 'Confectionery'), ('6', 'Unknow')], max_length=128)),
                ('approved_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.kid')),
            ],
        ),
    ]
