# Generated by Django 3.2.10 on 2021-12-28 20:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 20, 6, 23, 819017, tzinfo=utc), verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 20, 6, 23, 819017, tzinfo=utc), verbose_name='Updated on'),
        ),
    ]
