# Generated by Django 3.2.10 on 2021-12-28 20:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20211229_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 20, 7, 36, 104193, tzinfo=utc), verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 20, 7, 36, 104193, tzinfo=utc), verbose_name='Updated on'),
        ),
    ]
