# Generated by Django 3.2.10 on 2021-12-28 20:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20211229_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 20, 11, 15, 127943, tzinfo=utc), verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 20, 11, 15, 127943, tzinfo=utc), verbose_name='Updated on'),
        ),
    ]
